name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - run: cd MasterServer
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Copy frontend
      run: |
        mkdir -p MasterServer/bin/Debug/net6.0/frontend
        mkdir -p MasterServer/bin/Release/net6.0/frontend
        cp -r MasterServer/frontend/* MasterServer/bin/Debug/net6.0/frontend
        cp -r MasterServer/frontend/* MasterServer/bin/Release/net6.0/frontend
    - name: Upload Debug net6.0.zip
      uses: actions/upload-artifact@v3
      with:
        name: net6.0-Debug
        path: MasterServer/bin/Debug/net6.0
    - name: Upload Release net6.0.zip
      uses: actions/upload-artifact@v4
      with:
        name: net6.0-Release
        path: MasterServer/bin/Release/net6.0
